default: &default
  adapter: mysql2
  host: 192.168.1.101
  username: byml
  password: 123456
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: security_mgt_development

test:
  <<: *default
  database: security_mgt_test

production:
  <<: *default
  database: security_mgt_production
